"""002

Revision ID: 78b026a46957
Revises: 719e0da143ce
Create Date: 2023-12-24 15:11:05.154962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b026a46957'
down_revision: Union[str, None] = '719e0da143ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    op.drop_table('dish')
    op.drop_table('restaurant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.category_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dish_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('weight', sa.INTEGER(), nullable=True),
    sa.Column('final_price', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('updated_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dish', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['dish'], ['dish.dish_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
